### ISSUE TITLE
Running unit tests fail upon downloading PGP key

### ISSUE THREAD

**Issue by defuse** [paragonie/halite#1]
I tried to run the unit tests and got this error:

```
[firexware@firexware-pc halite]$ ./test/phpunit.sh 
gpg: error reading key: No public key
Downloading PGP Public Key...
gpg: keyserver receive failed: No keyserver available
gpg: error reading key: No public key
Could not download PGP public key for verification
```

Maybe a keyserver should be specified explicitly in the script?

**Comment by paragonie-scott** [comment]
Great point.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/961a26d4dd95612bee5d51a326536c40646c07c0

**Comment by defuse** [comment]
I can download the key now, but it fails with something else. I'll open a different ticket.

**Comment by defuse** [comment]
I opened #9 about the other issue. This one can be closed now.
