### ISSUE TITLE
A signing key is generated when trying to generate an encryption key when deriving from password

### ISSUE THREAD

**Issue by CodyCodeman** [paragonie/halite#10]
Taking simple case from docs.  When creating a symmetric encryption key it actually generates a signing key due to missing parenthesis.  Operator precedence in PHP evaluates `!==` operator before `&` operator.

```php
$salt = \Sodium\hex2bin(
    '762ce4cabd543065172236de1027536ad52ec4c9133ced3766ff319f10301888'
);

$enc_secret = Key::deriveFromPassword(
    'correct horse battery staple',
    $salt,
    Key::ENCRYPTION | Key::SECRET_KEY
);
```

**Comment by paragonie-scott** [comment]
> Operator precedence in PHP evaluates `!==` operator before `&` operator.

Seriously? That's surprising.

I'll add the necessary parentheses.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/b202f427062c29566b6ae09b1ee72b2bc1746d61 should resolve this (and prevent regressions down the road).

**Comment by paragonie-scott** [comment]
Thanks again @CodyCodeman for letting me know about this.
