### ISSUE TITLE
Constants defined twice in 3.x versions

### ISSUE THREAD

**Issue by driehle** [paragonie/halite#105]
In the 3.x versions, the `Sodium.stub.php` is added as an autoload file in composer.json and the `sodium_compat` packages is required as well:

https://github.com/paragonie/halite/blob/v3.x/composer.json

This leads to a lot of errors of constants which are defined twice:

```
PHP Notice:  Constant sodium\CRYPTO_AEAD_AES256GCM_KEYBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 8
PHP Notice:  Constant sodium\CRYPTO_AEAD_AES256GCM_NSECBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 9
PHP Notice:  Constant sodium\CRYPTO_AEAD_AES256GCM_NPUBBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 10
PHP Notice:  Constant sodium\CRYPTO_AEAD_AES256GCM_ABYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 11
PHP Notice:  Constant sodium\CRYPTO_AEAD_CHACHA20POLY1305_KEYBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 12
PHP Notice:  Constant sodium\CRYPTO_AEAD_CHACHA20POLY1305_NSECBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 13
PHP Notice:  Constant sodium\CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES already defined in C:\project\vendor\paragonie\halite\stub\Sodium.stub.php on line 14
[....]
```

I think this part your be removed from composer.json for the 3.x version of halite:

```
        "files": [
            "stub/Sodium.stub.php"
        ]
```

**Comment by paragonie-scott** [comment]
Just so you know, only Halite 4.0 and newer are supported as of today: https://github.com/paragonie/halite#installing-halite

**Comment by driehle** [comment]
So there is no supported version for PHP 7.1? I think this would be quite easy to fix and it would restore compatibility for PHP 7.1...

**Comment by paragonie-scott** [comment]
Not officially.

I'll still fix it, but supporting versions of PHP that don't have native libsodium support are massively unrewarding and so we decided to cut it off at 7.2. I *strongly* urge everyone to upgrade to Halite v4.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/releases/tag/v3.4.0 said that 3.4.0 was the final v3 release. I'm releasing v3.4.1 which is the final, final v3 release to fix this issue. Please make plans to upgrade to Halite 4.x and PHP 7.2 as soon as possible.
