### ISSUE TITLE
Compatible with .NET?

### ISSUE THREAD

**Issue by developer-variety** [paragonie/halite#109]
Is this repository compatible with .NET?
Especially with this [repository](https://github.com/adamcaudill/libsodium-net)?

Thank you.

**Comment by developer-variety** [comment]
Hey, thank you for replying.

I noticed it's not as soon as I started doing tests with it. I encrypted some data with my public key on the C# side and tried to decrypt it on PHP side and I just kept getting exceptions. Do you believe if I use sodium_compact it'll work?

**Comment by sstok** [comment]
sodium_compact is a Polyfill for when PHP doesn't support Sodium (older versions mainly), when you use libsodium for PHP it will (should) work as expected.

**Comment by developer-variety** [comment]
Well I was going to use it because I want a bare library of libsodium without the special things this library does. I love it and simplicity, but I want to replace RSA with it.

**Comment by paragonie-scott** [comment]
Halite implements high-level protocols on top of libsodium. It's possible to reimplement Halite in .NET, but that hasn't been done to my knowledge.

**Comment by developer-variety** [comment]
I'll be looking into it to see if I can make some time in my schedule to make it compatible.

**Comment by developer-variety** [comment]
I will be closing this issue since I have resolved it.

`libsodium-php` and `libsodium-net` are the way to go if you need `libsodium` on sever to client and vice versa.

Thank you for all who replied.
