### ISSUE TITLE
Extract HiddenString to separate package

### ISSUE THREAD

**Issue by alsar** [paragonie/halite#110]
Would it be possible to extract HiddenString to a separate package, which can be required by libraries and projects that need it without requiring the whole Halite package?

**Comment by paragonie-scott** [comment]
Yes, it's possible. Do you want to use HiddenString in other projects?

**Comment by paragonie-scott** [comment]
It might take a while before I can satisfy this request. https://twitter.com/packagist/status/993442665760002048

**Comment by alsar** [comment]
That was fast. :smile:
Thanks.
