### ISSUE TITLE
Unknown Downloader Type

### ISSUE THREAD

**Issue by Kabe0** [paragonie/halite#113]
Every time I run composer update with the halite composer lib included I get the following error...

`  Unknown downloader type: . Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.`

I don't have this problem on the first composer install. Any idea what's going on?

This is on all halite versions.

**Comment by paragonie-scott** [comment]
I have *no* idea. Is it still happening? It might be a Composer bug.

**Comment by paragonie-scott** [comment]
This appears to be a temporary Composer issue.
