### ISSUE TITLE
Use encryption key on a client

### ISSUE THREAD

**Issue by nico-dangerous** [paragonie/halite#115]
Hi,

I'm currently developping a client server app.
The server is written in PHP, so I use libsodium via halite. I'm generating an EncryptionKey once to encrypt string.
The client is written in .NET Xamarin C#. I would like to use this EncryptionKey inside the client.

I saved the EncryptionKey in a file and its content look like this : 31400400c7755192561990f14ee53e444d684cc3728a71475b33846f58f1d5be7fe49c41e138a5d9dcf14aa07c499b7924800e5592fd70ef053b1ba21d6cad3f5d175fb0301f9ed62da5b738f734f4b932d444c13dab1ecbe158af70a15394844e7133ea

I would like to know if someone can help me to use this key.
I'm using libsodium-net for the client but I don't how to get a 30 bytes haxadecimal from the string.

I tried to convert it to Hex but I get 200 bytes.

Could someone give me a hint ?

Thanks

**Comment by paragonie-scott** [comment]
Our key storage includes a prefix and a checksum.

https://github.com/paragonie/halite/blob/cbda59b8e39bfb02924cc6e2ee1c63accfda5da3/src/KeyFactory.php#L864-L871

If you want to naively import these keyfiles, you'll want to cut out the first 4 bytes and the latter 64 bytes (after hex-decoding).

Before:

```
31400400c7755192561990f14ee53e444d684cc3728a71475b33846f58f1d5be7fe49c41e138a5d9dcf14aa07c499b7924800e5592fd70ef053b1ba21d6cad3f5d175fb0301f9ed62da5b738f734f4b932d444c13dab1ecbe158af70a15394844e7133ea
```

After:

```
c7755192561990f14ee53e444d684cc3728a71475b33846f58f1d5be7fe49c41
```

**Comment by nico-dangerous** [comment]
Thank you very much !
