### ISSUE TITLE
MutableFile constructed with string assumes that file exists

### ISSUE THREAD

**Issue by Furgas** [paragonie/halite#116]
Is this desired behaviour that we should create the output file before calling ex. `File::encrypt()`? What's the reasoning?

**Comment by beeare** [comment]
> 
> 
> Is this desired behaviour that we should create the output file before calling ex. `File::encrypt()`? What's the reasoning?

In older versions of halite it was not required, so it seems to be a change that should be reviewed - Is it really desired behaviour?

**Comment by beeare** [comment]
`https://github.com/paragonie/halite/commit/454d9df7baeddc1365e629537186ca1a0906e574` was the commit with that change in MutableFile class.

**Comment by Furgas** [comment]
Good to know. So, I guess, it should be answered by the commit author.

**Comment by duronrulez** [comment]
Any news on this? We are having similar issues after upgrading to latest version. Do we really need to have the output file created prior to passing it to encrypt?

**Comment by paragonie-scott** [comment]
D'oh! `WritableFile` should be allowed to not exist before creation. This *is* a bug. I'll fix it ASAP.

**Comment by paragonie-scott** [comment]
This is fixed in `v4.5.2`. Thanks for reporting it.
