### ISSUE TITLE
HiddenString BC Break in Minor Version

### ISSUE THREAD

**Issue by rickogden** [paragonie/halite#124]
In the latest minor version update (4.4 -> 4.5), HiddenString is moved to a new package (and therefore new namespace). This breaks code when you perform a composer update. There should either be a (deprecated) HiddenString class still in the old namespace, or this should be a major release.

**Comment by paragonie-scott** [comment]
I don't have a religious devotion to semver, but okay.

**Comment by paragonie-scott** [comment]
`v4.5.1` is released, contains a unit test to ensure the `class_alias()` is working.

The `HiddenString` class is `final`, so I can't just make another class extend it.

**Comment by rbairwell** [comment]
Sorry for reopening this issue, but I've just been hit with a similar issue (main code base switched to using Paragonie\HiddenString\HiddenString, but then hitting incompatibilities with Halite where it'll only accept Paragonie\Halite\HiddenString ).

What's your thoughts on having Paragonie\HiddenString\HiddenStringInterface , change Halite to support that type and then have just have the actual HiddenString classes be copies of each other (namespaced appropriately) which then extend HiddenStringInterface?

I know there's a possibility that someone could then make an insecure HiddenStringInterface supporting class and get it on the server, but if they are able to do that, they can probably amend the code in vendor/ anyway.
