### ISSUE TITLE
 Fatal error: Uncaught SodiumException: Not using the native libsodium bindings

### ISSUE THREAD

**Issue by Mayze123** [paragonie/halite#148]
Here's my code , i don't know where the error is comming from
$data = [
    'FirstName' => 'John',
    'LastName' => 'smith',
    'Adress' => '6678 rue toutdroit'
];

line 77 -> $prepared = $row->prepareRowForStorage($data);

What may be the issue ?

**Comment by paragonie-security** [comment]
Wrong repository. You're looking for https://github.com/paragonie/ciphersweet instead.

https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium
