### ISSUE TITLE
Pseudorandom key generation in hkdfBlake2b() function

### ISSUE THREAD

**Issue by padraigdoran** [paragonie/halite#149]
https://github.com/paragonie/halite/blob/6b21367ecd02c6aa844ad791a0d985b953aa2550/src/Util.php#L140

```
// HKDF-Extract:
// PRK = HMAC-Hash(salt, IKM)
// The salt is the HMAC key.
$prk = self::raw_keyed_hash($ikm, $salt);
```

In the above lines the code generates a PRK (pseudorandom key). The $prk value is used later on in that same function.

My question is, are the $ikm and $salt parameters passed in the wrong order on line 140?

**Comment by paragonie-security** [comment]
The notation is backwards. HKDF uses `Key, Message` while the  API uses `Message, Key`.
