### ISSUE TITLE
Can Halite be used with Swoole/ReactPHP in PHP Applications?

### ISSUE THREAD

**Issue by raghuveer** [paragonie/halite#150]
I would like to understand if we can use Halite in applications, those that are developed in non-blocking I/O, asynchronous perspectives, using any of the following and alikes,

a) Swoole, https://www.swoole.co.uk/
b) ReactPHP, https://reactphp.org/

Being a regular Halite User, we are considering to include Halite library, to handle Cryptographic activities in our applications, where we aspire to use Swoole/ReactPHP kind of solutions

thank you

**Comment by raghuveer** [comment]
any suggestion about this?

**Comment by paragonie-security** [comment]
Seems related to #159

**Comment by raghuveer** [comment]
will wait for php 8.1 and compatible Halite release

**Comment by paragonie-security** [comment]
Upon closer review, the main complication is the file operations for loading/saving keys...which are optional.

**Comment by paragonie-security** [comment]
See comment in #159
