### ISSUE TITLE
Add support for SameSite cookie flag in PHP 7.3+

### ISSUE THREAD

**Issue by zealsolutions** [paragonie/halite#153]
Since PHP 7.3 [introduced support for the `samesite` flag for cookies](https://www.php.net/manual/en/migration73.other-changes.php) and Halite is security-focused, it would be good to add support for this feature.

Backwards-compatibility considerations: The options for this cookie are `None`, `Lax`, or `Strict`, and "If the samesite element is omitted, no SameSite cookie attribute is set" [(`setcookie()` docs](https://www.php.net/manual/en/function.setcookie.php)).

We don't want to inadvertently break existing uses of this library by silently making things more strict when upgrading the PHP version, so I think it would be prudent to omit the option unless it is explicitly set by the user.

**Comment by paragonie-security** [comment]
Thanks! This will be released in v4.7.0
