### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by arcticlinux** [paragonie/halite#157]
I've just been doing some preliminary testing with PHP 8.  I didn't test everything but the only thing stopping me from running in PHP 8 with how I'm using Halite was that MB_OVERLOAD_STRING was removed in 8.0.

paragonie/sodium_compat/src/Core/Util.php:915
```
((int) (ini_get('mbstring.func_overload')) & MB_OVERLOAD_STRING);
```

I just defined that constant for my rather limited testing.

```
if (!defined('MB_OVERLOAD_STRING')) {
    define('MB_OVERLOAD_STRING', 2);
}
```

**Comment by paragonie-security** [comment]
This is a sodium_compat issue, not a Halite issue, but we'll fix it upstream.

**Comment by paragonie-security** [comment]
https://github.com/paragonie/sodium_compat/commit/13a615518edfdbca006c86fdc984c162d956a41a

**Comment by arcticlinux** [comment]
The only other thing was in composer.json, but that has been resolved as well.

**Comment by spaze** [comment]
PHP 8 throws a warning when using `final private`, #158
