### ISSUE TITLE
export/import string Asymmetric-Key Encryption keypair?

### ISSUE THREAD

**Issue by wivaku** [paragonie/halite#168]
Would like to export/import a keypair to/from string.

The [basic documentation](https://github.com/paragonie/halite/blob/master/doc/Basic.md#encryption) shows that, for the encryption key in Symmetric-Key Encryption, I can save to / import from string.

In my case I am generating a [keypair](https://github.com/paragonie/halite/blob/master/doc/Classes/KeyFactory.md#generateencryptionkeypair) for **A**symmetric-Key Encryption. 

I am having trouble to import (and export?) the keys.  
I tried:
```
use ParagonIE\Halite\KeyFactory;
$keys = KeyFactory::generateEncryptionKeyPair();  // ParagonIE\Halite\EncryptionKeyPair
$keys->getPublicKey()->isPublicKey(); // true
$keys_hex = KeyFactory::export($keys)->getString(); // string

$keys = KeyFactory::importEncryptionKey(new HiddenString($keys_hex)); // ParagonIE\Halite\Symmetric\EncryptionKey
$keys->getPublicKey(); // undefined method ParagonIE\Halite\Symmetric\EncryptionKey::getPublicKey
```

So: the import returns an `EncryptionKey` instead of the wanted `EncryptionKeyPair`.

Two questions:
- the [KeyFactory documentation](https://github.com/paragonie/halite/blob/master/doc/Classes/KeyFactory.md) does not mention the `export()` and `importEncryptionKey()` methods?
- can the export / import also be used for keypairs?

**Comment by wivaku** [comment]
For the export: the `save()` documentation mentions it accepts `key` or `keypair`.  
The string in the saved file and the string from `export()` are identical.  
So I assume export works for both `key` or `keypair`.

**Comment by wivaku** [comment]
never mind! 
Should have used `KeyFactory::importEncryptionKeyPair(new HiddenString($keys_hex))`
So, only the question about documentation remains.

**Comment by paragonie-security** [comment]
See #177 for changes to make this more apparent
