### ISSUE TITLE
Switch to ChaCha20 for symmetric encryption

### ISSUE THREAD

**Issue by anthony-o** [paragonie/halite#170]
The [ANSSI](https://en.wikipedia.org/wiki/Agence_nationale_de_la_s%C3%A9curit%C3%A9_des_syst%C3%A8mes_d%27information) ( French National Agency for the Security of Information Systems) recommends in its "[Cryptographic algorithms selection guide](https://www.ssi.gouv.fr/uploads/2021/03/anssi-guide-selection_crypto-1.0.pdf)" that for symmetric encryption, AES should be preferred for bloc encryption (3.1 - R1 in the guide), and Chacha20 for stream encryption (3.2 - R2 in the guide).

I've saw in the source that Halite uses [`\sodium_crypto_stream_xor`](https://github.com/paragonie/halite/blob/7596d5cb25154092b524c34cb9ce2201db612ffc/src/Symmetric/Crypto.php#L284) which [uses XSalsa20](https://www.php.net/manual/fr/function.sodium-crypto-stream-xor.php) cipher and not ChaCha20 one.

I've tried to replace the 2 calls (encryption / decryption) with the ChaCha20 equivalents (`\sodium_crypto_aead_chacha20poly1305_ietf_encrypt` / `\sodium_crypto_aead_chacha20poly1305_ietf_decrypt`) with success but as I am not a crypto expert, I'm not sure if the key derivation that is currently used before this call & the authentication functions after are still OK to use with this encryption / decryption function.

**Comment by paragonie-security** [comment]
We aren't going to ever switch to ChaCha20. We *might* switch to [XChaCha20](https://php.watch/versions/8.1/Sodium-XChaCha20-functions).

We're investigating other changes for Halite 5, which will almost certainly stop using Xsalsa20 and target PHP 8.1 and newer.

**Comment by anthony-o** [comment]
Thank you for your answer. Any reason to choose XChaCha20 against ChaCha20?

**Comment by paragonie-security** [comment]
XChaCha20 has a 192-bit nonce instead of a 96-bit nonce, which changes the risk of random nonce collision to "roughly one in a billion after a few billion messages" to "virtually never".

**Comment by anthony-o** [comment]
OK thank you for those explanations.

Anyway, as I'm working for a project that must follow the guide I initially posted in this thread, I must encrypt my app data using ChaCha20 and I didn't find other serious high level crypto library in PHP that would do this "the good way" (except using AES implementation by defuse but it is faaaar slower that halite symmetric encryption using XSalsa20 (more that 700 times slower) or my modified version using ChaCha20).

As you seem to have knowledge @paragonie-security , do you know if switching from XSalsa20 to ChaCha20 in halite code is as simple as just replacing encrypt / decrypt / generating key / constants for nonces etc, and keep the key derivation & authentication just like it is already coded?

I could perhaps post a PR (which obviously would not be accepted as it is not planned for halite to switch to ChaCha20) in this "issue" in order to better illustrate what I did?

**Comment by paragonie-security** [comment]
> do you know if switching from XSalsa20 to ChaCha20 in halite code is as simple as just replacing encrypt / decrypt / generating key / constants for nonces etc, and keep the key derivation & authentication just like it is already coded?

We generally don't recommend making changes to Halite. We're already planning on switching the stream cipher in v5.

**Comment by paragonie-security** [comment]
Done in #176 :)
