### ISSUE TITLE
Asymmetric authenticated file encryption/decryption

### ISSUE THREAD

**Issue by Toflar** [paragonie/halite#174]
First of all: Thank you so much for investing so much time and effort in making the PHP world a safer place <3 

This is probably just a rather stupid question but the library implements both, anonymous and authenticated asymmetric encryption . However, I could not see support for it in the `File` helper. It does seem to support "only" anonymous asymmetric encryption.
Is this on purpose or is it just missing?

The fact that the library otherwise seems so complete just made me a bit unsure about things now :D

**Comment by paragonie-security** [comment]
Correct, it only supports anonymous asymmetric encryption. The underlying encryption is IND-CCA2 secure, but the sender identity isn't authenticated.

Its omission was definitely not intentional. We'll consider adding it in Halite 5.

**Comment by Toflar** [comment]
Thanks for the reassuring and quick reply!

**Comment by paragonie-security** [comment]
This is already included in the v5 dev branch https://github.com/paragonie/halite/pull/176
