### ISSUE TITLE
phpunit.sh should exit 1 upon PGP key fingerprint checking failure

### ISSUE THREAD

**Issue by defuse** [paragonie/halite#3]
```
    if [ $? -ne 0 ]; then
        echo -e "\033[31mCould not download PGP public key for verification\033[0m"
        exit
    fi
```

That should be an `exit 1`, else something that only checks the exit code could think the test passed when it was really under attack.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/961a26d4dd95612bee5d51a326536c40646c07c0

**Comment by defuse** [comment]
LGTM

**Comment by defuse** [comment]
(also nice catch, i missed that one)
