### ISSUE TITLE
\ParagonIE\Halite\File::decrypt fails when running on laravel homestead

### ISSUE THREAD

**Issue by TimeToogo** [paragonie/halite#33]
I am having issues using this library for encrypting / decrypting files.

What is strange is that everything works as expected when running PHP via the cli. Yet running it through nginx (php-fpm) seems to cause issues and the decryption fails consistently with the following error:

`Fatal error: Uncaught ParagonIE\Halite\Alerts\InvalidMessage: Invalid message authentication code`

I am running running PHP 7 on the laravel homestead environment.

I narrowed it down to the following script:

```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

@mkdir(__DIR__ . '/enc/');
file_put_contents(__DIR__ . '/enc/test.txt', 'This is a test');

$key = \ParagonIE\Halite\KeyFactory::deriveEncryptionKey('password', str_repeat('a', 16));
@unlink(__DIR__ . '/enc/encrypted');
@unlink(__DIR__ . '/enc/decrypted.txt');

\ParagonIE\Halite\File::encrypt(__DIR__ . '/enc/test.txt', __DIR__ . '/enc/encrypted', $key);
\ParagonIE\Halite\File::decrypt(__DIR__ . '/enc/encrypted', __DIR__ . '/enc/decrypted.txt', $key);
```

`\ParagonIE\Halite\Halite::isLibsodiumSetupCorrectly()` returns `true`

The following
```php
var_dump([
    $major = \Sodium\library_version_major(),
    $minor = \Sodium\library_version_minor(),
]);
```
outputs `array(2) { [0]=> int(9) [1]=> int(2) }`

And I followed the instructions to compile libsodium from the source from this blog article:
https://paragonie.com/book/pecl-libsodium/read/00-intro.md

Thanks in advance

**Comment by paragonie-scott** [comment]
What line number is it being thrown from?

**Comment by TimeToogo** [comment]
Here is the stack trace (some directories omitted):

```
<br />
<b>Fatal error</b>:  Uncaught ParagonIE\Halite\Alerts\InvalidMessage: Invalid message authentication code in /home/vagrant/.../vendor/paragonie/halite/src/File.php:1149
Stack trace:
#0 /home/vagrant/.../vendor/paragonie/halite/src/File.php(451): ParagonIE\Halite\File::streamVerify(Object(ParagonIE\Halite\Stream\ReadOnlyFile), NULL, Object(ParagonIE\Halite\Config))
#1 /home/vagrant/.../vendor/paragonie/halite/src/File.php(107): ParagonIE\Halite\File::decryptData(Object(ParagonIE\Halite\Stream\ReadOnlyFile), Object(ParagonIE\Halite\Stream\MutableFile), Object(ParagonIE\Halite\Symmetric\EncryptionKey))
#2 /home/vagrant/.../public/index.php(13): ParagonIE\Halite\File::decrypt('/home/vagrant/p...', '/home/vagrant/p...', Object(ParagonIE\Halite\Symmetric\EncryptionKey))
#3 {main}
  thrown in <b>/home/vagrant/.../vendor/paragonie/halite/src/File.php</b> on line <b>1149</b><br />
```

**Comment by paragonie-scott** [comment]
That's interesting. I've confirmed the bug with FPM as well. I'll let you know as soon as I figure out what's happening.

**Comment by paragonie-scott** [comment]
I think I got it.

https://github.com/paragonie/halite/commit/3611fe8daf5401eb6faa4d91e878be7e6867fd7a Can you checkout master and verify that this fixed the problem for you?

**Comment by paragonie-scott** [comment]
I also did a slight refactor for readability: https://github.com/paragonie/halite/commit/a0ca360c36390e4bd4818b4206d64c900a75ff7f

**Comment by TimeToogo** [comment]
Yep, working as expected now, thanks for the fast response.

**Comment by paragonie-scott** [comment]
Thanks for reporting this. :)

I've released 2.0.1 with the fix in place.

**Comment by Vincent--** [comment]
I have this error message with php 5.6 (fpm)

`Uncaught Exception ParagonIE\Halite\Alerts\InvalidMessage: "Invalid message authentication code" at /rginstall/vendor/paragonie/halite/src/File.php line 1442 {"exception":"[object] (ParagonIE\\Halite\\Alerts\\InvalidMessage(code: 0): Invalid message authentication code at /rginstall/vendor/paragonie/halite/src/File.php:1442)"} []
`

Could that be the same issue? Is there a backport available?

**Comment by paragonie-scott** [comment]
While I really don't want to touch PHP 5 code ever again, I can backport this if need be, since it's an edge case bug.

**Comment by Vincent--** [comment]
Our issue was due to a missing directory actually, no need for a fix.
Sorry for the false alert...
