### ISSUE TITLE
Network Stream and AEAD

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/halite#35]
Placeholder ticket. Investigate the usefulness of having:

* `ParagonIE\Halite\Network\`
   * `NonceProvider\`
      * `PDOProvider`
      * `RandomProvider`
      * `ProviderInterface`
         * `getNonce()` get a nonce and increase the stored value (for PDO)
   * `Crypto`
      * `encrypt()` using `\Sodium\crypto_aead_encrypt()` after CAESAR
      * `decrypt()` using `\Sodium\crypto_aead_decrypt()` after CAESAR
      * Would require a nonce provider, which is stateful

This might be a useless idea. You should be using TLS.

**Comment by alfiepates** [comment]
**-1.**

You should be using TLS.

**Comment by defuse** [comment]
What's the proposal? Need a bit more detail to understand what's being proposed.

**Comment by paragonie-scott** [comment]
The idea is to create an API for network-layer encryption that uses AEAD modes and interacts with PHP's native stream features.

It would come with a nonce provider interface in case developers are working with protocols that specify their own nonce requirements. It would exclusively use the CAESAR winner, whenever that is decided.

This doesn't tackle, e.g. key exchange, although we could build that into it too. I'd hesitate to rebuild something like X.509 or ASN.1 because that's completely insane, and you should be using TLS for that anyway.

So an example implementation might look like:

```php
use \ParagonIE\Halite\Network\Crypto as Netcrypto;
use \ParagonIE\Halite\Network\RandomProvider;
use \ParagonIE\Halite\KeyFactory;

$serverPublicKey = KeyFactory::loadEncryptionPublicKey('/path/to/pinned_public_key');

$server = new Netcrypto('127.0.0.1:8254', $serverPublicKey, new RandomProvider());
// Invoked implicitly on first run:
    $sessionKey = $server->refreshSessionKeys();

// Send data to the server:
$received = $server->send("This is some data to encrypt", "this is some data to authenticate");
```

Under the hood, `refreshSessionKeys()` will generate an ephemeral key pair, seal $clientPublicKey using $serverPublicKey along with a challenge nonce, then send it to the server. The server will decrypt it, seal the nonce back to the client's socket, encrypted with the client's public key.

`send()` would use `crypto_aead_*()` to encrypt a message, write it to a network stream, then read the response.

-----

But this seems way too feature bloaty and might serve as a separate project entirely, should we decide it needs to exist.

**Comment by paragonie-scott** [comment]
Consensus: Use TLS. That's what it's there for.

**Comment by defuse** [comment]
Yeah, I'd almost certainly miss bugs in something like that.
