### ISSUE TITLE
Feedback Sought From Halite Users

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/halite#36]
I'm considering whether to flag the API as stable and put this in "maintenance only" mode in Paragon's internal docs, but before I do, what (if anything) does Halite currently not do that you'd like to see it do before it's done?

**Comment by clayfreeman** [comment]
Hopefully this isn't a sign of ceasing development on this project — it would be better in my opinion to freeze the current API but allow for future additions of features to provide a mix of compatibility and ability to expand.

Currently there is nothing on my wish list for Halite; it does everything that I could want.  Thanks for taking the time to make this project and your continuous effort to improve the adoptability of secure-by-design practices.

**Comment by paragonie-scott** [comment]
> Hopefully this isn't a sign of ceasing development on this project — it would be better in my opinion to freeze the current API but allow for future additions of features to provide a mix of compatibility and ability to expand.

If we do cease development, we'll pick it back up whenever it's needed. I just think I've managed to eliminate most of the technical debt (aside from documentation).

I should probably write better documentation. Beyond that, it seems like Halite is complete. (Until post-quantum crypto lands in libsodium in a few years.)

**Comment by paragonie-scott** [comment]
Okay, it's settled. More docs, fix bugs if any crop up, but otherwise I think we're done.
