### ISSUE TITLE
crypto_box_seal is not available

### ISSUE THREAD

**Issue by Elbana** [paragonie/halite#39]
when I use Halite\Asymmetric\Crypto::seal it throw exception crypto_box_seal is not available I had a look into the method and function_exists('\\Sodium\\crypto_box_seal') return false when it has leading slash but function_exists('Sodium\\crypto_box_seal') it return true 

i am using Halite 1.0.5

**Comment by paragonie-scott** [comment]
> function_exists('\Sodium\crypto_box_seal') return false when it has leading slash but function_exists('Sodium\crypto_box_seal') it return true

That's... interesting. The leading slash just says "start from the global namespace". i.e.

```php
namespace Foo\Sodium {
    function crypto_box_seal() {
        // backdoor!
    }
}
namepsace Foo {
    function bar() {
        $x = Sodium\crypto_box_seal(/* ... */);
    }

    function baz() {
        $x = \Sodium\crypto_box_seal(/* ... */);
    }
}
```
The only difference between the two is that `baz()` is explicit, but `bar()` will call `Foo\Sodium\crypto_box_seal()` first. Assuming no maliciously named function (in a namespace) exists, they should both resolve to the same destination.

**Comment by Elbana** [comment]
the function is working when i comment the check for the function exist but for some reason function_exists don't return false always , is there anything we can do around this check ?

**Comment by paragonie-scott** [comment]
I don't know. That sounds like a PHP bug. What version of PHP are you running?

**Comment by Elbana** [comment]
I am using 5.6

**Comment by remicollet** [comment]
I cannot reproduce (5.6, 7.0)

BTW, try to use \\ instead of \

**Comment by Elbana** [comment]
Hi remicollet, it is already used inside Asymmetric\Crypto::seal with double slashes I am just calling seal method but getting this error

**Comment by Elbana** [comment]
can we use is_callable() instead of function_existes() ?

**Comment by clayfreeman** [comment]
@Elbana Which PHP version are you using so that I can try to reproduce?

**Comment by Elbana** [comment]
Hi @clayfreeman  I am using 5.6.23 thanks.

**Comment by clayfreeman** [comment]
@Elbana Could you run `\ParagonIE\Halite::isLibsodiumSetupCorrectly(true);` and paste the output as well?

**Comment by paragonie-scott** [comment]
That method didn't exist in the version 1 branch, which is the only one that supported PHP 5.

```php
        // Require libsodium 1.0.9
        $major = \Sodium\library_version_major();
        $minor = \Sodium\library_version_minor();
        if ($major < 9 || ($major === 9 && $minor < 2)) {
            if ($echo) {
                echo 'Halite needs libsodium 1.0.9 or higher. You have: ',
                \Sodium\version_string(), "\n";
            }
            return false;
        }
        return true;
    }
```

**Comment by clayfreeman** [comment]
```
root@ubuntu:~/project# php main.php 
PHP CLI 5.6.11-1ubuntu3.4
Check if function exists with global namespace:    true
Check if function exists without global namespace: true
```

```php
<?php
  require_once(__DIR__.'/vendor/autoload.php');
  echo "PHP CLI ".phpversion()."\n";
  echo "Check if function exists with global namespace:    ";
  echo var_export(function_exists('\\Sodium\\crypto_box_seal'), true)."\n";
  echo "Check if function exists without global namespace: ";
  echo var_export(function_exists('Sodium\\crypto_box_seal'), true)."\n";
```

Unable to reproduce on Ubuntu 15.10 with PHP 5.6.11 using CLI, latest tag on libsodium's repo, and latest version of PECL libsodium.

**Comment by Elbana** [comment]
Thanks guys for your help really appreciate it 

isLibsodiumSetupCorrectly() true

var_dump([
    \Sodium\library_version_major(),
    \Sodium\library_version_minor(),
    \Sodium\version_string()
]);

array (size=3)
  0 => int 9
  1 => int 2
  2 => string '1.0.10' (length=6)

PHP CLI 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
Check if function exists with global namespace:    false
Check if function exists without global namespace: true

**Comment by clayfreeman** [comment]
@Elbana It appears as though you're trying to use the PHP 7 branch with PHP 5, at least from what @paragonie-scott said earlier in this thread:

> That method didn't exist in the version 1 branch, which is the only one that supported PHP 5.

Make sure that you're using at most v1.5.0 of Halite; anything newer supports PHP 7 only.

**Comment by Elbana** [comment]
Hi @clayfreeman I am using Halite v1.5.0 I just copied the method to my files.

**Comment by paragonie-scott** [comment]
@Elbana Did you, perchance, install the PECL extension against an older version of libsodium then upgrade libsodium? If so, uninstall then reinstall the PECL extension, which was probably compiled against an older version.

**Comment by Elbana** [comment]
uninstall ok: channel://pecl.php.net/libsodium-1.0.6
install ok: channel://pecl.php.net/libsodium-1.0.6

still the same

**Comment by paragonie-scott** [comment]
1. Uninstall PECL libsodium.
2. Uninstall libsodium.
3. Compile libsodium stable (1.0.10) from source.
4. Install PECL libsodium.

**Comment by Vincent--** [comment]
I have the same issue and apparently it's related to the suhosin module... I don't know why for the moment however.

```
# cat /rginstall/Test.php
<?php

require_once(__DIR__.'/vendor/autoload.php');
echo "PHP CLI ".phpversion()."\n";

if (extension_loaded('suhosin')) {
	echo "With suhosin enable\n";
} else {
	echo "With suhosin disable\n";
}

echo "Check if function exists with global namespace:    ";
echo var_export(function_exists('\\Sodium\\crypto_box_seal'), true)."\n";
echo "Check if function exists without global namespace: ";
echo var_export(function_exists('Sodium\\crypto_box_seal'), true)."\n";

//var_dump(get_extension_funcs('libsodium'));
```

The output is:

```
PHP CLI 5.6.21-1+donate.sury.org~trusty+4
With suhosin disable
Check if function exists with global namespace:    true
Check if function exists without global namespace: true


PHP CLI 5.6.21-1+donate.sury.org~trusty+4
With suhosin enable
Check if function exists with global namespace:    false
Check if function exists without global namespace: true
```

**Comment by Vincent--** [comment]
See https://github.com/stefanesser/suhosin/issues/92

**Comment by paragonie-scott** [comment]
Oh, interesting!

**Comment by Vincent--** [comment]
Any idea how to fix it? Couldn't we use is_callable() instead of function_exists() maybe ? I'm not sure this will be patch on the suhosin side soon and I think a lot of people use both suhosin and halite...

**Comment by paragonie-scott** [comment]
`is_callable()` works in Suhosin as expected? If so, I'll release a patch for 1.x and 2.x that makes this change.

**Comment by paragonie-scott** [comment]
Proposed changes:

* Version 1 branch: https://github.com/paragonie/halite/commit/452f19ee8391c8d272635254a4dabbe702327d2a
* Version 2 branch: https://github.com/paragonie/halite/commit/0120005d600dec19ec3aabeef29a621c74087ba6
* Version 3 branch (master): https://github.com/paragonie/halite/commit/030b6fbc91177810eef000442b4cb53b1dbc5f7e

If you could please confirm that this fixes the problem for you, I'll tag & sign new releases.

**Comment by Elbana** [comment]
@paragonie-scott This does fix the issue for me thanks guys for looking into this and thanks @Vincent-- for pointing the issue.
