### ISSUE TITLE
Documentation is confusing with regards to HiddenString

### ISSUE THREAD

**Issue by BlackHoleOrNeutronStar** [paragonie/halite#42]
---IGNORE THIS COMMENT---

This isn't an issue, but an earlier discussion said to ask for help here, so:

I'm trying to run a pretty simple Halite example (shown below).

```
<?php
require_once 'vendor/autoload.php';

use ParagonIE\Halite\HiddenString;
use ParagonIE\Halite\KeyFactory;
use ParagonIE\Halite\Symmetric\Crypto as Symmetric;

$encryptionKey = KeyFactory::loadEncryptionKey('/var/key/9.key');

$message = new HiddenString('This is a confidential message for your eyes only.');
$ciphertext = Symmetric::encrypt($message, $encryptionKey);

$decrypted = Symmetric::decrypt($ciphertext, $encryptionKey);

var_dump($decrypted === $message); // bool(true)

?>
```

However, the program always breaks at `new HiddenString();`, for a reason that I can't seem to understand. If anyone has any insight, or can offer any help, that would be most appreciated. Thank you so much!

Debian Jessie
Raspberry Pi Model B
PHP 5.6.24-0+deb8u1
Halite: v1.5.1
PECL extention: v1.0.6
Composer: v1.2.0

Thanks!

**Comment by BlackHoleOrNeutronStar** [comment]
Update:
From reading Issue #41 , I found out that Hidden String is not supposed to be used in Halite version 1 or 2. If this could be made clearer in the documentation provided and examples, that would be much appreciated.

Thank you!

**Comment by yarcowang** [comment]
Direct comparing `var_dump($decrypted === $message); // bool(true)` seems returning **false**.
Maybe it is good to add an `equal` method in `HiddenString` for they have already defined the class.

**Comment by paragonie-scott** [comment]
I think this can be closed? Comparing two `HiddenString` objects is a separate issue.
