### ISSUE TITLE
Compile Error in Symmetric Crypto

### ISSUE THREAD

**Issue by usmanzafar** [paragonie/halite#44]
I recently started using Password hashing function which seems very promising in my web app which happens to be using Symfony framework, however it appears that the Symmetric Crypto file is giving a Compile Error as per the debug component (which comes very handy to debug common bugs etc). 

This is the exact error given by Symfony debug component.

> Compile Error: Cannot use ParagonIE\Halite\Config as Config because the name is already in use

Here is the stack trace that can provide more insight into the problem.

1. Entry level: i am calling the verify method in my code.
`Password::verify($password, $hash, $this->encKey);`

2. This hits the verify function in **_paragonie/halite/src/Password.php_** (line 155)
`        $hash_str = Crypto::decrypt($stored, $secretKey);`

3. This hits the _**paragonie/halite/src/Symmetric/Crypto.php**_ and gives the above mentioned error. Specific code that gets highlighted is 
`use ParagonIE\Halite\{
    Config,`

Solution: It appears that we do not require base Config  to be referred in **_paragonie/halite/src/Symmetric/Crypto.php_** as Symmetric / Config is the one which should be doing most of the job here anyways.  Secondly, splitKey function should use SymmetricConfig as required parameter rather then Config (line 196)

Let me know if above solution makes sense and i can send a quick PR.

Lastly great work by @paragonie-scott - this lib makes crypto such a pain free process.

![compileerror](https://cloud.githubusercontent.com/assets/1739406/19300815/0470adbc-90a8-11e6-9449-43d585ca524e.png)

**Comment by usmanzafar** [comment]
Hey guys, any update on this ?
@paragonie-scott with above assumption may i submit a PR or do you reckon it could be another way to fix this.

**Comment by sstok** [comment]
This is indeed a bug, as you can't import a class from another namespace when that class already exists in the current namespace.

As a Quick fix you can alias the import like `ConfigLocal` and replace the occurrence in this file.

**Comment by paragonie-scott** [comment]
Yeah, what version are you using? I've been focusing on `3.x` but that obviously won't help if you're still using `2.x` :P

**Comment by finwe** [comment]
I am getting this too when running PHPUnit tests and an error occurs. It is super annoying. Aliasing Config use statement in Symmetric\Crypto to anything non-generic (HaliteConfig) seems to help, though I may have not understood the code well enough to know this is the correct solution.

That's for version 3.1.

**Comment by usmanmetronome** [comment]
Hey @paragonie-scott , any update on the new tag release taking care of this ?
