### ISSUE TITLE
How to install halite on ubuntu 16.04 and php7

### ISSUE THREAD

**Issue by aolko** [paragonie/halite#48]
Assuming that you don't have build utils, php7 devtools, git, pear&pecl, composer (fresh install)
## Libsodium
1. Get build utils
   `sudo apt-get install build-essential`
2. Get php7.0-dev
   `sudo apt-get install php7.0-dev`
    *Or php7.1-dev/php7.2-dev*
    `sudo apt-get install php7.1-dev`
    `sudo apt-get install php7.2-dev`
3. Git (good)
   `sudo apt-get install git`
4. Get libsodium

```
# Clone the libsodium source tree & Build libsodium, perform any defined tests, install libsodium
git clone -b stable https://github.com/jedisct1/libsodium.git && cd libsodium && ./configure && make check && make install
```
1. Get PEAR & PECL
   `sudo apt-get install pear`
2. Install libsodium from PECL
   `pecl install libsodium` (*or `pecl install -f libsodium-2.0.8` according to comments*)
3. Get straight to **/etc/php/<PHP_VERSION>/mods-available/** and make a `libsodium.ini` file (*Where <PHP_VERSION> is 7.0 or 7.1 or 7.2*)
4. Write down `extension=libsodium.so` (*or `sodium.so` according to comments*) in `libsodium.ini` & save (**Yes, it works like this now**, no more php.ini bs)
5. Enable the libsodium mod
`sudo phpenmod libsodium`
6. Reload PHP
   `sudo /etc/init.d/apache2 restart && service php7.0-fpm restart`
7. Check for libsodium with `php -m`
## Halite
1. Get composer
   `sudo apt-get install composer`
2. Navigate to your php project folder and install halite
   `composer require paragonie/halite`
3. Done

**Comment by paragonie-scott** [comment]
This sounds like it'd be a great contribution to https://github.com/paragonie/pecl-libsodium-doc

**Comment by aolko** [comment]
trust me, it worth me sweat, tears and a slight bump on my forehead

**Comment by paragonie-security** [comment]
Note: If https://github.com/paragonie/sodium_compat is successfully finished and audited, I may release a new minor version that doesn't have the PECL extension as a hard dependency, thus making this easier to use.

**Comment by Evergreenn** [comment]
Hi, before reloading php you have to enable the mod
`sudo phpenmod libsodium`
Otherwise it will not be linked in **/etc/php/7.0/apache2/conf.d**

**Comment by aolko** [comment]
fixed

**Comment by DeftNerd** [comment]
This really helped me, thanks... one note, on Linux Mint (based on Ubuntu), I had to run ```apt-get install php-pear``` instead of ```apt-get install pear```

I don't know if this is Mint specific or if the package name has changed in the Xenial base.

**Comment by pascal-hofmann** [comment]
You can also use the PPA from Ondřej Surý: https://launchpad.net/~ondrej/+archive/ubuntu/php

Package name is `php-sodium`.

**Comment by tersmitten** [comment]
@pascal-hofmann 

For us that package does not seem to work:

```
# bin/test/php.sh 

Welcome to CakePHP v2.10.2 Console
---------------------------------------------------------------
App : app
Path: /vagrant/www/foo.dev-app/app/
---------------------------------------------------------------
CakePHP Test Shell
---------------------------------------------------------------
Error: Call to undefined function Sodium\hex2bin()
#0 /vagrant/www/foo.dev-app/app/Vendor/paragonie/halite/src/KeyFactory.php(486): ParagonIE\Halite\KeyFactory::loadKeyFile('/vagrant/www/fo...')
```

**Comment by pascal-hofmann** [comment]
@tersmitten Strange. Works for me. If you have installed it and it is enabled you should see info about it when you run `php -i` and also `find /etc/php/ -name '*sodium*'` should look similar to this:

> /etc/php/7.0/mods-available/sodium.ini
> /etc/php/7.0/cli/conf.d/20-sodium.ini
> /etc/php/7.0/fpm/conf.d/20-sodium.ini
> /etc/php/7.1/mods-available/sodium.ini

**Comment by paragonie-scott** [comment]
@tersmitten Upgrade to Halite 3.3.0 and it ought to work?

**Comment by tersmitten** [comment]
@paragonie-scott Works like a charm!

**Comment by v1n11** [comment]
Hi All,

I'm struggling since days to install libsodium on my Debian9/php7.0(with fpm) server ...
When I follow the steps outlined above everything seems to work, however I get this error at PHP startup:

Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....

So the extension is not loaded ...

Hope someone can help me,
Thx !
Vincent.

**Comment by tersmitten** [comment]
@v1n11 How do you install `extensions`? Using the Debian repositories, https://deb.sury.org/ or something else?

**Comment by v1n11** [comment]
Hi tersmitten,
I'm not sure what you mean ... I installed libsodium from the source (github) and then I installed the PHP extension through pear.
I also added the sodium.so file to the ini file, but it looks like PHP can't load that so file.
Many thanks for your help !!!!

**Comment by paragonie-scott** [comment]
Try `pecl install libsodium-2.0.7`

**Comment by v1n11** [comment]
paragonie-scott,
Just tried that and I get:
pecl/libsodium is already installed and is newer than detected released version 2.0.7
installation failed

**Comment by dmitriy-olhovsky** [comment]
Have the same issue on debian 9 & php7 - "Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....".

**Comment by v1n11** [comment]
paragonie-scott,
I now first did pecl uninstall libsodium and then pecl install libsodium-2.0.7 like you said and now it seems to work

If I run
<?php
var_dump([
    SODIUM_LIBRARY_MAJOR_VERSION,
    SODIUM_LIBRARY_MINOR_VERSION,
    SODIUM_LIBRARY_VERSION
]);

I get:

array(3) { [0]=> int(10) [1]=> int(0) [2]=> string(6) "1.0.15" }


Any idea why the newer version did not work ?

Thx !

**Comment by paragonie-security** [comment]
No, but updating one of my servers to 2.0.9 yields the same result. Hmmm.

**Comment by jedisct1** [comment]
`pecl install -f libsodium-2.0.8` should work, even if the code is the same.

**Comment by v1n11** [comment]
Indeed, version 2.0.8 works fine as well ... Thanks.

**Comment by Evergreenn** [comment]
Hi guys, now during the installation, PECL shows you that the extension must be named as `extension=sodium.so` in your .ini file, maybe due to php7.2 and it native implementation of this lib.

**Comment by paragonie-security** [comment]
Yes, `sodium.so` is needed for version 2.

**Comment by aolko** [comment]
My guide is still fully related?
