### ISSUE TITLE
Suggestion for HiddenString

### ISSUE THREAD

**Issue by clayfreeman** [paragonie/halite#49]
I would like that `HiddenString` cannot be revealed via `serialize(...)`; this can be achieved by the `__sleep()` magic method returning an empty array.  Would this fit within the scope of what `HiddenString` sets out to achieve?

**Comment by paragonie-scott** [comment]
Well, the goal is to stop leaks in stack traces from uncaught exceptions, not to prevent all possible leaks from all possible feature misuse.

But I can implement this easily.

**Comment by clayfreeman** [comment]
This will be a nice feature to have because now only `var_export(...)` is able to see protected/private members and can be disabled via `disable_functions` if desired.

If you have better things to do, I can implement this as an optional feature and submit a pull request later today so that you don't have to worry with this.

**Comment by paragonie-scott** [comment]
This is in 3.2.0
