### ISSUE TITLE
Missing ] error in Travis-CI output

### ISSUE THREAD

**Issue by defuse** [paragonie/halite#5]
I noticed this:

```
./test/phpunit.sh: line 34: [: missing `]'
```

at

https://travis-ci.org/paragonie/halite/jobs/84852786

**Comment by paragonie-scott** [comment]
Whitespace issue.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/961a26d4dd95612bee5d51a326536c40646c07c0

**Comment by defuse** [comment]
LGTM
