### ISSUE TITLE
Libsodium not available in PHPStorm

### ISSUE THREAD

**Issue by frederikbosch** [paragonie/halite#50]
I see you have a beautiful Sodium stub in this package. It is possible to [create a PR here](https://github.com/JetBrains/phpstorm-stubs) to embed this directly into PHPStorm. Would you be so kind to create the PR? Or, for sure, I can create it for you, if you give me permission to do so.

**Comment by paragonie-scott** [comment]
Sort of like https://github.com/JetBrains/phpstorm-stubs/pull/78 perhaps?

**Comment by frederikbosch** [comment]
Cool! And I did not see that PR. Thanks for your work already!
