### ISSUE TITLE
compitible with php5.5.9

### ISSUE THREAD

**Issue by totoleo** [paragonie/halite#51]
Hello, I do some work to make it compitible with php5.5.9. I don`t know whether it is OK to merge my work into your branch. #52

**Comment by paragonie-scott** [comment]
Hi,

While I do appreciate the effort put into this, it makes little sense for a security library to support a version of PHP [that no longer receives security updates](https://secure.php.net/supported-versions.php).

@ircmaxell made the case for [sane PHP minimum version requirements](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html), and we encourage more projects to stick to only supported versions of PHP.

If you need to continue supporting PHP 5.5.9 for purely internal reasons, we encourage you to use your own fork of Halite.

Thanks,
Scott

**Comment by paragonie-scott** [comment]
I probably should clarify a few minor things (some tangential):

My employer's current plan is to stop supporting Halite 1 entirely once PHP 5.6 is no longer supported by the PHP team, and to focus on a 4.0 branch when libsodium has landed in PHP 7.2. Among other reasons for this decision: We run a [bug bounty program](http://hackerone.com/paragonie), and if we're supporting a vulnerable, abandoned version of PHP, we'll end up paying for it (literally).

When the time for deprecation comes, a lot of companies and hobbyists stuck on PHP 5 may greatly value a fork (for which you can decide your own policies).

If you wish to host the "PHP 5.5.9 fork of Halite", all you need to do is:

1. Change the name in composer.json from `paragonie/halite` to `totoleo/halite` (or if you have a preferred vendor namespace, feel free to use that).
2. Submit your fork to Packagist.

I'd like to emphasize that I greatly value your work and the effort you put into this, but I worry about the impact of dragging the minimum version backwards will have on future development. Should you wish to pursue this, I have no problem updating the README files pointing people to your fork for PHP 5.5.9+ support.

**Comment by totoleo** [comment]
It's my pleasure for your response. I'm also pushin updating work of PHP7 forward in my company.
At last, thank again for your advises.

**Comment by paragonie-scott** [comment]
I'm going to close this, as our scope is moving towards 7.2 not towards 5.5.
