### ISSUE TITLE
Documentation confusing for KeyFactory::deriveEncryptionKey in Halite1

### ISSUE THREAD

**Issue by tstrijdhorst** [paragonie/halite#57]
Documentation mentions the following

https://github.com/paragonie/halite#example-generating-a-key-from-a-password 

Relevant Excerpt:
```php
$salt = "\xdd\x7b\x1e\x38\x75\x9f\x72\x86\x0a\xe9\xc8\x58\xf6\x16\x0d\x3b";

$encryptionKey = KeyFactory::deriveEncryptionKey($passwd, $salt);
```

In Halite1 the salt needs to be binary format not a hex encoded string. Or else you will get the exception:

> salt should be CRYPTO_PWHASH_SCRYPTSALSA208SHA256_SALTBYTES bytes

**Comment by paragonie-scott** [comment]
Fun fact: The `\x` escapes hex codes into raw binary. https://3v4l.org/7LYGX

**Comment by tstrijdhorst** [comment]
@paragonie-scott is this behaviour specific to some version of the PHP Interpreter? I literally used the code in the example at the time and got the error I mentioned. After using hex2bin it did work.

**Comment by paragonie-scott** [comment]
It won't work with single quotes, but it will work with double quotes.

**Comment by tstrijdhorst** [comment]
Ah ok, thanks for the explanation. PHP gonna PHP I guess.
