### ISSUE TITLE
KeyFactory::generateEncryptionKey returning nothing

### ISSUE THREAD

**Issue by udf2457** [paragonie/halite#64]
PHP 7.1.8 (cli) (built: Aug 17 2017 14:29:52) ( NTS 
halite 3.2.0

Am I doing something stupid ?

```
$enc_key = \ParagonIE\Halite\KeyFactory::generateEncryptionKey();
echo strlen($enc_key).PHP_EOL;
```

Seems to return zero ?   Base64 wrapping $enc_key returns nothing ?   Have I missed a step ?

**Comment by paragonie-scott** [comment]
This isn't returning a string, it's returning an object. This is covered in [the basic documentation](https://github.com/paragonie/halite/blob/master/doc/Basic.md#symmetric-key-encryption).

If you really truly 100% need the string contents? First, **make sure what you're doing isn't going to introduce a security vulnerability**. If you don't know, [we consult](https://paragonie.com/contact).

If and only if you're confident that your approach isn't dangerous: `$enc_key->getRawKeyMaterial()` returns the internal string encapsulated by `Key` objects.

**Comment by udf2457** [comment]
Aah... that makes sense now.  I will go sit in the corner with a dunce hat.

Certainly not planning to introduce a security vulnerability, its just that I needed the key in string form and not a file.  "Red" key string will be automagically turned into a "Black" key string through something plugged into my computer. ;-)

**Comment by paragonie-scott** [comment]
```php
$hiddenString = $key->export();
$saveToConfig = $hiddenString->getString();

$loadedFromConfig = new HiddenString("...");
$reloaded = KeyFactory::importEncryptionKey($hiddenString);
```

**Comment by paragonie-scott** [comment]
Note that here's an `import_____Key()` method in `KeyFactory` for all of the cryptography key types in Halite :)

**Comment by udf2457** [comment]
Now you're just showing off. :)

P.S. Thanks for the awesome libraries that help bring a little security to a language with a bit of a reputation !
