### ISSUE TITLE
php-libsodium - 2.x Available (BC Break)

### ISSUE THREAD

**Issue by tersmitten** [paragonie/halite#65]
* https://github.com/oerdnj/deb.sury.org/issues/659
* https://github.com/oerdnj/deb.sury.org/issues/685
* #48 

> It needs to be fixed in halite, not the other way around. The old libsodium.so has been deprecated by the author, and the API has changed, so anything depending on libsodium.so needs to be fixed to use the new API.

What do you think?

**Comment by pascal-hofmann** [comment]
For me updating halite to 3.3.0 fixed all issues with the new php-sodium package. Did you try that?

**Comment by tersmitten** [comment]
No.. You are right, updating also fixes the problem for us :-)

```
# composer update paragonie/halite
Loading composer repositories with package information
Updating dependencies (including require-dev)                                               
Package operations: 0 installs, 1 update, 0 removals
  - Updating paragonie/halite (v3.2.0 => v3.3.0): Downloading (100%)         
```

https://github.com/paragonie/halite/releases
