### ISSUE TITLE
Issue during installation of Airship CMS 

### ISSUE THREAD

**Issue by pahan12** [paragonie/halite#66]
i successfully install php7.2
now going to install libsodium from this link https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium

after installing i tried `phpenmod libsodium` and it gives following error
`WARNING:` Module libsodium ini file doesn't exist under /etc/php/7.0/mods-available`

now i goto airship cms install and type  `composer install`
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-libsodium ^1.0.6 is missing from your system. Install or enable PHP's libsodium extension.
  Problem 2
    - Installation request for paragonie/halite v2.2.0 -> satisfiable by paragonie/halite[v2.2.0].
    - paragonie/halite v2.2.0 requires ext-libsodium ^1.0.6 -> the requested PHP extension libsodium is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
    - /etc/php/7.0/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
`

i tried to install it more that 20 times and evrytime same errror libsodium
any help?

**Comment by paragonie-scott** [comment]
It looks like your `php` command is going to PHP 7.0 rather than PHP 7.2.

**Comment by pahan12** [comment]
Yeah, 
I first completely removed php7.0 
Then I installed php7.2, after that I install I successfully install libsodium. 
So all dependency in done,  now I goto airship and type `composer install ` and it says command not found,. 
So I install it using 'apt install composer'  and this this command install php7.0 composer and some other php7.0  module. 
Now then I type `composer install` and it gives ext-libsodium not install and the following error

Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested PHP extension ext-libsodium ^1.0.6 is missing from your system. Install or enable PHP's libsodium extension.
Problem 2
- Installation request for paragonie/halite v2.2.0 -> satisfiable by paragonie/halite[v2.2.0].
- paragonie/halite v2.2.0 requires ext-libsodium ^1.0.6 -> the requested PHP extension libsodium is missing from your system.

To enable extensions, verify that they are enabled in those .ini files:
- /etc/php/7.0/cli/php.ini
- /etc/php/7.0/cli/conf.d/10-opcache.ini
- /etc/php/7.0/cli/conf.d/10-pdo.ini
- /etc/php/7.0/cli/conf.d/15-xml.ini
- /etc/php/7.0/cli/conf.d/20-calendar.ini
- /etc/php/7.0/cli/conf.d/20-ctype.ini
- /etc/php/7.0/cli/conf.d/20-dom.ini
- /etc/php/7.0/cli/conf.d/20-exif.ini
- /etc/php/7.0/cli/conf.d/20-fileinfo.ini
- /etc/php/7.0/cli/conf.d/20-ftp.ini
- /etc/php/7.0/cli/conf.d/20-gd.ini
- /etc/php/7.0/cli/conf.d/20-gettext.ini
- /etc/php/7.0/cli/conf.d/20-iconv.ini
- /etc/php/7.0/cli/conf.d/20-json.ini
- /etc/php/7.0/cli/conf.d/20-mbstring.ini
- /etc/php/7.0/cli/conf.d/20-phar.ini
- /etc/php/7.0/cli/conf.d/20-posix.ini
- /etc/php/7.0/cli/conf.d/20-readline.ini
- /etc/php/7.0/cli/conf.d/20-shmop.ini
- /etc/php/7.0/cli/conf.d/20-simplexml.ini
- /etc/php/7.0/cli/conf.d/20-sockets.ini
- /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
- /etc/php/7.0/cli/conf.d/20-sysvsem.ini
- /etc/php/7.0/cli/conf.d/20-sysvshm.ini
- /etc/php/7.0/cli/conf.d/20-tokenizer.ini
- /etc/php/7.0/cli/conf.d/20-wddx.ini
- /etc/php/7.0/cli/conf.d/20-xmlreader.ini
- /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
- /etc/php/7.0/cli/conf.d/20-xsl.ini
- /etc/php/7.0/cli/conf.d/20-zip.ini

**Comment by paragonie-scott** [comment]
What does this command output?

```sh
which php
```

Also, those version requirements are weird. Try `git reset --hard HEAD && git pull origin master`?

**Comment by pahan12** [comment]
I will give u  a new ssh access,  can you please set   up airship?

**Comment by pahan12** [comment]
command:=> `which php`
output:=> `/usr/local/bin/php`
command:=> `git reset --hard HEAD && git pull origin master`
output: =>
_**HEAD is now at 0692c86 Version 1.4.3
remote: Counting objects: 70, done.
remote: Total 70 (delta 57), reused 57 (delta 57), pack-reused 13
Unpacking objects: 100% (70/70), done.
From https://github.com/paragonie/airship
 * branch            master     -> FETCH_HEAD
   1d92318..ccc588a  master     -> origin/master

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@user-X550CA.(none)')**_

=====================================================================
i tried all step in this docs 
https://github.com/paragonie/airship-docs/blob/master/en-us/01-intro/2-Installing.md
https://github.com/paragonie/halite/issues/48
https://github.com/paragonie/airship-docs/blob/master/en-us/01-intro/2-Installing.md
https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium
even tried to intsall with fresh linux server but every time libsodium errror dispite of successfully libsodium installed

if u want u can setup my ssh server , it mostly take 5-6 minute
server:  ubuntu@18.221.148.63
key: 
[private_key.zip](https://github.com/paragonie/halite/files/1393345/private_key.zip)

**Comment by pahan12** [comment]
is it possible to setup Airship CMS in windows 8.1?

**Comment by mabar** [comment]
@pahan12 Do you think it is good idea to upload your PRIVATE key somewhere where it can be downloaded by everyone?

**Comment by pahan12** [comment]
@mabar
I created this ssh server only for airship and it does not have any sensitive info. 

I see this is only way to setup airship CMS if airship member help. 
I trying for last 6 days and everytime  same error

**Comment by pahan12** [comment]
Can you please resolve this problem?
What should be my next step?

**Comment by paragonie-scott** [comment]
First, you're going to want to purge your server *anyway*. Then, for the easiest path forward, wait until December and install PHP 7.2 on a server that PHP has never been installed on, so you don't get these conflicts.

If you're impatient, `apt-get purge php7.0-.*` ought to get rid of all traces of PHP 7.0. Then you're left with only 7.2 (I hope).

**Comment by paragonie-scott** [comment]
I'm going to close this as it's more of an Airship question than a Halite question.
