### ISSUE TITLE
Do file handles get closed when a later exception is thrown?

### ISSUE THREAD

**Issue by defuse** [paragonie/halite#8]
For example:

https://github.com/paragonie/halite/blob/master/src/File.php#L42

Does `$inputhandle` get closed when that exception is thrown?

**Comment by paragonie-scott** [comment]
No, but it should.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/103ccedde5d6127d11fd65059923e1d68cf102dd

**Comment by defuse** [comment]
Is it possible for the `encryptResource()`, `decryptResources()`, etc. to throw an exception?

**Comment by paragonie-scott** [comment]
Yes, and I see why you're asking. :)

**Comment by defuse** [comment]
I've never, ever, seen a `finally` block in real code. Maybe this is one of those times where it's actually worth using? :P

**Comment by paragonie-scott** [comment]
Not quite a `finally` block, but https://github.com/paragonie/halite/commit/3bf8479cddbac60e9df0f10675c7eaf50cc023ca

**Comment by defuse** [comment]
LGTM.

**Comment by paragonie-scott** [comment]
Excellent. Thanks :)
