### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by JeromeGill** [paragonie/halite#89]
A number of errors of this nature...

!!  PHP Fatal error:  Cannot redeclare Sodium\crypto_aead_aes256gcm_is_available() (previously declared in vendor/paragonie/sodium_compat/lib/sodium_compat.php:70) in vendor/paragonie/halite/stub/Sodium.stub.php on line 70

**Comment by paragonie-scott** [comment]
Wait, why are you including the stub? That's just for IDEs to autocomplete libsodium correctly.

**Comment by JeromeGill** [comment]
I'm actually requiring a DoctrineBundle that lists  paragonie/halite as a dependency. Something is off with the composer settings, I'm not too sure where yet.

https://github.com/michaeldegroot/DoctrineEncryptBundle/blob/master/composer.json

**Comment by paragonie-scott** [comment]
This will likely help: https://github.com/michaeldegroot/DoctrineEncryptBundle/pull/2

**Comment by JeromeGill** [comment]
Fantastic :+1:  Thank you

**Comment by paragonie-scott** [comment]
I'm pushing a final release of the v3 branch and marking all old versions as deprecated to prevent these problems going forward.
