### ISSUE TITLE
Trying to run the unit test can't find autoload.php

### ISSUE THREAD

**Issue by defuse** [paragonie/halite#9]
```
PHPUnit 5.0.5 by Sebastian Bergmann and contributors.

Cannot open file "/home/firexware/egits/halite/vendor/autoload.php".
```

**Comment by paragonie-scott** [comment]
Try running `composer update` first.

**Comment by defuse** [comment]
```
[firexware@firexware-pc zerocashd]$ composer update
bash: composer: command not found
```

lol, I guess I'll have to install composer first

**Comment by defuse** [comment]
I totally ran that in the wrong folder, too. Need break from computer.

**Comment by paragonie-scott** [comment]
I can create an `/autoload.php` script and make it provide feedback of `vendor/autoload.php` is not found (and also whitelist the files that actually exist). It might make it easier for people without composer to use.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/commit/ee5e92ee65dfebf26b7d8c559921ce2a5d4cf76c ought to fix it. Please feel free to re-open if it doesn't.

**Comment by defuse** [comment]
Ah, didn't realize that was a composer thing. +1 for being able to run tests without composer.
