### ISSUE TITLE
Util::safeStrcpy cant handle single character strings

### ISSUE THREAD

**Issue by merk** [paragonie/halite#97]
If you try to create a HiddenString instance with a single character string, Util::safeStrcpy will go into an infinite loop.

I'd attempt a fix but I'm not sure whats intended. Should $chunk always be >= 1? There are no tests covering this function that would provide context.

https://github.com/paragonie/halite/blob/43d595580673a596b25949a3502f8ab6142317d4/src/Util.php#L275

**Comment by JulesPrimo** [comment]
I just faced the same problem.
For my culture, what's the point of the safeStrcpy method ? Why split and recompose the string ?

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/halite/blob/43d595580673a596b25949a3502f8ab6142317d4/src/Util.php#L263-L264

**Comment by paragonie-scott** [comment]
This is fixed in v4.4.1. https://github.com/paragonie/halite/releases/tag/v4.4.1

Thanks for reporting this to me. Sorry for not getting the fix out sooner, it's been a rough few weeks. 👍
