### ISSUE TITLE
Uncaught SodiumException ( not possible to securely wipe memory)

### ISSUE THREAD

**Issue by udf2457** [paragonie/halite#99]
> "PHP message: PHP Fatal error:  Uncaught SodiumException: This is not implemented, as it is not possible to securely wipe memory from PHP in vendor/paragonie/sodium_compat/src/Compat.php:2569
> Stack trace:
> vendor/paragonie/sodium_compat/lib/sodium_compat.php(792): ParagonIE_Sodium_Compat::memzero()
> vendor/paragonie/halite/src/HiddenString.php(82): Sodium\memzero()
> vendor/paragonie/halite/src/Asymmetric/EncryptionSecretKey.php(26): ParagonIE\Halite\HiddenString->__destruct()
> local/XYZ/CryptoTools.php(38): ParagonIE\Halite\Asymmetric\EncryptionSecretKey->__construct()

**Comment by paragonie-scott** [comment]
Install libsodium. For example: https://github.com/paragonie/halite/blob/master/doc/Install-Guides/Ubuntu.md

**Comment by MelodicCrypter** [comment]
NEED HELP...

Fatal error: Uncaught SodiumException: This is not implemented, as it is not possible to securely wipe memory from PHP in /home/melodi14/public_html/mcclicks.com/vendor/paragonie/sodium_compat/src/Compat.php:2483 Stack trace: #0 /home/melodi14/public_html/mcclicks.com/vendor/paragonie/sodium_compat/lib/php72compat.php(849): ParagonIE_Sodium_Compat::memzero('\x12\xD8G\xFE%\x8F}\xC0]\xA3\xAER\x9E\x0E_...') #1 /home/melodi14/public_html/mcclicks.com/vendor/paragonie/halite/src/KeyFactory.php(106): sodium_memzero('\x12\xD8G\xFE%\x8F}\xC0]\xA3\xAER\x9E\x0E_...') #2 /home/melodi14/public_html/mcclicks.com/src/MCClasses/Security.php(12): ParagonIE\Halite\KeyFactory::generateEncryptionKeyPair() #3 /home/melodi14/public_html/mcclicks.com/register.php(154): KVapp\Security::createUserKeys('kv29a767') #4 {main} thrown in /home/melodi14/public_html/mcclicks.com/vendor/paragonie/sodium_compat/src/Compat.php on line 2483

**Comment by paragonie-scott** [comment]
The solution I mentioned in my previous comment is the same that applies to your error.

1. Make sure you're on PHP 7.2.
2. If libsodium isn't enabled, add `ext=sodium.so` to your php.ini
3. If libsodium isn't even installed, first complain to your OS vendor and then do the equivalent of `apt-get install php7.2-sodium`.

**Comment by MelodicCrypter** [comment]
Thank you for your response.

I already added the extension to the PHP 7.2 ini

However, my server's default PHP version is 5.6, but 7.2 is already installed in a diffrent directory through WHM. How can I install Libsodium into that PHP 7.2 directory? My server is Centos.

**Comment by paragonie-scott** [comment]
I honestly have no idea, I don't use CentOS.

Are you on shared hosting? It might be an Apache configuration setting that your hosting provider may have to fiddle with.

The supported versions of Halite all require PHP 7.2.

**Comment by MelodicCrypter** [comment]
I've managed to use the path of PHP 7.2. So basically,

I'm on Centos 7.4 using PHP 7.2

Libsodium is already installed, but when I checked the phpinfo(), I can't see the Libsodium details. I have successfully installed Libsodium on my local machine but on my web server, there have to be some issues. 

This is what would result if I'll install the Libsodium on Centos using Yum

> Package libsodium-devel-1.0.16-1.el7.x86_64 already installed and latest version

It's already installed. I really don't know what to do now.

**Comment by paragonie-scott** [comment]
I think the best person to ask if PHP 7.2 for CentOS 7.4 includes ext/sodium support already or not would be @remicollet (whom, I believe, manages PHP 7.2 for CentOS etc.?)

**Comment by paragonie-scott** [comment]
OK, if it's not, `yum install php-pecl-libsodium2` might do the trick?

https://rpms.remirepo.net/enterprise/7/php72/x86_64/repoview/php-pecl-libsodium2.html

**Comment by remicollet** [comment]
Try `yum install php-sodium`

**Comment by DazDotOne** [comment]
Just to add to @remicollet's comment you may still need to add `extension=sodium.so` to your `php.ini`.

I'm running php in a centos7 docker image.

I had to add the following to my Dockerfile:
````Docker
RUN yum install libsodium-devel -y
RUN yum install php-sodium -y
RUN echo "extension=sodium.so" >>  /etc/php.ini
````

_Note:_ I had to have the `libsodium-devel` and `php-sodium` install lines separated as `php-sodium` wasn't actually installing when they were on the same line.

In a non-docker CentOS system, remove the `RUN` part and you may need to use `sudo`.

running `php -m` will tell you which modules have been loaded.

**Comment by remicollet** [comment]
@DazDotOne notice that using RPM (so yum install php-sodium), you never have to change the php.ini.  The package provides its own php.d/20-sodium.ini. 

RPM installed = extension enabled.

**Comment by DazDotOne** [comment]
Thanks for that @remicollet but as I said, using docker, for some reason sodium wasn't loading until I added it.

I just thought it was worth adding to the conversation.

**Comment by DazDotOne** [comment]
Thanks for that @remicollet.

I can confirm that is indeed the case. 

However, again, as I'm working in a dockerized environment, it wouldn't load without it yesterday. I can only assume there's some form of caching that happens on the container that was preventing it from loading correctly.

Now that I have restarted my machine, I've removed that line and it seems to be loading correctly.

**Comment by magentobinary** [comment]
> 
> 
> Just an update: I've managed to install Libsodium extension by using WHM > Module Installers > PHP Pecl > Libsodium
> 
> Thanks.

This solution is work for me.
Thanks
